// Base de datos de recetas para el menú infantil (6 meses - 5 años)
// grupoEdad: '6-9' (puré fino), '9-12' (puré con grumos / finger food), '1-5' (sólido)
// comida: 'comida' (almuerzo) | 'cena'
// etiquetas: usadas para excluir por alergia o por "no le gusta"
// preparacion: breve explicación de cómo hacer la receta

const RECIPES = [
  // ---------------------------------------------------------------
  // 6-9 MESES · COMIDA (puré fino, sin sal ni azúcar)
  // ---------------------------------------------------------------
  { id: 'c69-01', nombre: 'Puré de calabacín, patata y pollo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pollo'],
    preparacion: 'Cuece la pechuga de pollo, la patata y el calabacín troceados en agua sin sal hasta que estén tiernos (15-20 min). Tritura todo junto con un poco del caldo de cocción y el aceite de oliva hasta obtener una textura fina y sin grumos.',
    ingredientes: [
      { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Pechuga de pollo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-02', nombre: 'Puré de zanahoria, arroz y merluza', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pescado'],
    preparacion: 'Cuece la zanahoria y el arroz en agua hasta que estén muy blandos; añade la merluza los últimos 5 minutos. Tritura todo con un poco de caldo y el aceite hasta que quede fino y colado.',
    ingredientes: [
      { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Arroz', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' },
      { nombre: 'Merluza', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-03', nombre: 'Puré de calabaza, patata y pavo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pavo'],
    preparacion: 'Cuece la calabaza, la patata y la pechuga de pavo troceadas hasta que estén tiernas. Tritura con un poco del agua de cocción y el aceite de oliva hasta lograr una crema fina.',
    ingredientes: [
      { nombre: 'Calabaza', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Pechuga de pavo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-04', nombre: 'Puré de judía verde, patata y ternera', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['ternera'],
    preparacion: 'Cuece la judía verde, la patata y la ternera troceada hasta que todo esté muy tierno. Tritura con caldo de cocción y aceite de oliva hasta conseguir una textura lisa.',
    ingredientes: [
      { nombre: 'Judía verde', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Ternera', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-05', nombre: 'Puré de puerro, patata y lenguado', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pescado', 'puerro'],
    preparacion: 'Cuece el puerro y la patata; añade el lenguado los últimos 5 minutos de cocción. Tritura todo junto con un poco de caldo y aceite de oliva hasta que quede fino y sin espinas.',
    ingredientes: [
      { nombre: 'Puerro', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Lenguado', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-06', nombre: 'Puré de brócoli, patata y pollo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pollo', 'brocoli'],
    preparacion: 'Cuece el brócoli, la patata y el pollo troceados hasta que estén blandos. Tritura con caldo de cocción y aceite de oliva hasta obtener una textura fina.',
    ingredientes: [
      { nombre: 'Brócoli', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Pechuga de pollo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-07', nombre: 'Puré de guisantes, arroz y pavo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pavo', 'guisantes'],
    preparacion: 'Cuece los guisantes, el arroz y el pavo hasta que estén tiernos. Tritura con un poco de caldo y aceite de oliva, colando si quedan pieles de guisante.',
    ingredientes: [
      { nombre: 'Guisantes', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Arroz', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' },
      { nombre: 'Pechuga de pavo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-08', nombre: 'Puré de calabacín, boniato y merluza', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pescado'],
    preparacion: 'Cuece el calabacín, el boniato y la merluza hasta que estén tiernos. Tritura todo con un poco de caldo de cocción y aceite de oliva hasta lograr una crema fina.',
    ingredientes: [
      { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Merluza', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-09', nombre: 'Puré de zanahoria, calabaza y pollo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pollo'],
    preparacion: 'Cuece la zanahoria, la calabaza y el pollo troceados hasta que estén blandos. Tritura con caldo de cocción y aceite de oliva hasta conseguir una textura homogénea.',
    ingredientes: [
      { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Calabaza', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Pechuga de pollo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-10', nombre: 'Puré de acelga, patata y ternera', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['ternera', 'acelga'],
    preparacion: 'Cuece la acelga, la patata y la ternera hasta que estén tiernas. Tritura con caldo de cocción y aceite de oliva, colando si quedan fibras.',
    ingredientes: [
      { nombre: 'Acelga', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Ternera', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-11', nombre: 'Puré de espinacas, patata y pollo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pollo', 'espinacas'],
    preparacion: 'Cuece las espinacas, la patata y el pollo hasta que estén tiernos. Tritura con un poco de caldo y aceite de oliva hasta obtener una crema fina.',
    ingredientes: [
      { nombre: 'Espinacas', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Pechuga de pollo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-12', nombre: 'Puré de coliflor, patata y merluza', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pescado', 'coliflor'],
    preparacion: 'Cuece la coliflor y la patata; añade la merluza los últimos 5 minutos. Tritura todo con caldo de cocción y aceite de oliva hasta que quede fino.',
    ingredientes: [
      { nombre: 'Coliflor', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Merluza', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-13', nombre: 'Puré de calabacín, arroz y ternera', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['ternera'],
    preparacion: 'Cuece el calabacín, el arroz y la ternera troceada hasta que estén tiernos. Tritura con caldo de cocción y aceite de oliva hasta lograr una textura lisa.',
    ingredientes: [
      { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Arroz', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' },
      { nombre: 'Ternera', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-14', nombre: 'Puré de zanahoria, patata y lenguado', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pescado'],
    preparacion: 'Cuece la zanahoria y la patata; añade el lenguado los últimos 5 minutos. Tritura todo con caldo y aceite de oliva, comprobando que no queden espinas.',
    ingredientes: [
      { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Lenguado', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-15', nombre: 'Puré de boniato, guisantes y pavo', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pavo', 'guisantes'],
    preparacion: 'Cuece el boniato, los guisantes y el pavo hasta que estén tiernos. Tritura con caldo de cocción y aceite de oliva hasta conseguir una crema fina.',
    ingredientes: [
      { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' },
      { nombre: 'Guisantes', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Pechuga de pavo', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c69-16', nombre: 'Puré de calabaza, arroz y merluza', grupoEdad: '6-9', comida: 'comida',
    textura: 'Triturado fino y colado', etiquetas: ['pescado'],
    preparacion: 'Cuece la calabaza y el arroz; añade la merluza los últimos 5 minutos. Tritura todo con caldo de cocción y aceite de oliva hasta que quede fino.',
    ingredientes: [
      { nombre: 'Calabaza', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' },
      { nombre: 'Arroz', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' },
      { nombre: 'Merluza', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },

  // ---------------------------------------------------------------
  // 6-9 MESES · CENA (puré ligero, sin proteína animal o con muy poca)
  // ---------------------------------------------------------------
  { id: 'n69-01', nombre: 'Puré de calabaza y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la calabaza y la patata hasta que estén muy tiernas. Tritura con un poco de agua de cocción y el aceite de oliva hasta obtener una crema fina.',
    ingredientes: [ { nombre: 'Calabaza', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-02', nombre: 'Puré de calabacín y arroz', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece el calabacín y el arroz hasta que estén blandos. Tritura con un poco de caldo y aceite de oliva hasta conseguir una textura lisa.',
    ingredientes: [ { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Arroz', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-03', nombre: 'Crema de zanahoria y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la zanahoria y la patata hasta que estén tiernas. Tritura con caldo de cocción y aceite de oliva hasta lograr una crema fina y homogénea.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-04', nombre: 'Puré de guisantes y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['guisantes'],
    preparacion: 'Cuece los guisantes y la patata hasta que estén tiernos. Tritura con caldo de cocción y aceite de oliva, colando si quedan pieles.',
    ingredientes: [ { nombre: 'Guisantes', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-05', nombre: 'Puré de judía verde y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la judía verde y la patata hasta que estén muy blandas. Tritura con un poco de caldo y aceite de oliva hasta que quede fino.',
    ingredientes: [ { nombre: 'Judía verde', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-06', nombre: 'Puré de puerro y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['puerro'],
    preparacion: 'Cuece el puerro y la patata hasta que estén tiernos. Tritura con caldo de cocción y aceite de oliva hasta obtener una crema fina.',
    ingredientes: [ { nombre: 'Puerro', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-07', nombre: 'Puré de brócoli y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['brocoli'],
    preparacion: 'Cuece el brócoli y la patata hasta que estén blandos. Tritura con caldo de cocción y aceite de oliva hasta lograr una textura lisa.',
    ingredientes: [ { nombre: 'Brócoli', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-08', nombre: 'Crema de calabacín y boniato', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece el calabacín y el boniato hasta que estén tiernos. Tritura con un poco de caldo y aceite de oliva hasta conseguir una crema fina.',
    ingredientes: [ { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-09', nombre: 'Puré de acelga y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['acelga'],
    preparacion: 'Cuece la acelga y la patata hasta que estén tiernas. Tritura con caldo de cocción y aceite de oliva, colando si quedan fibras.',
    ingredientes: [ { nombre: 'Acelga', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-10', nombre: 'Puré de zanahoria y calabacín', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la zanahoria y el calabacín hasta que estén blandos. Tritura con un poco de caldo y aceite de oliva hasta que quede fino.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-11', nombre: 'Puré de espinacas y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['espinacas'],
    preparacion: 'Cuece las espinacas y la patata hasta que estén tiernas. Tritura con caldo de cocción y aceite de oliva hasta obtener una crema fina.',
    ingredientes: [ { nombre: 'Espinacas', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-12', nombre: 'Puré de coliflor y patata', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['coliflor'],
    preparacion: 'Cuece la coliflor y la patata hasta que estén blandas. Tritura con caldo de cocción y aceite de oliva hasta lograr una textura lisa.',
    ingredientes: [ { nombre: 'Coliflor', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-13', nombre: 'Crema de boniato y manzana', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['manzana'],
    preparacion: 'Cuece el boniato; añade la manzana pelada y troceada los últimos 5 minutos. Tritura todo junto con un poco de agua de cocción hasta obtener una crema suave y ligeramente dulce.',
    ingredientes: [ { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Manzana', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n69-14', nombre: 'Puré de calabaza y arroz', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la calabaza y el arroz hasta que estén tiernos. Tritura con caldo de cocción y aceite de oliva hasta conseguir una crema fina.',
    ingredientes: [ { nombre: 'Calabaza', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Arroz', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-15', nombre: 'Crema de judía verde y boniato', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la judía verde y el boniato hasta que estén blandos. Tritura con un poco de caldo y aceite de oliva hasta lograr una textura fina.',
    ingredientes: [ { nombre: 'Judía verde', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'n69-16', nombre: 'Puré de zanahoria y puerro', grupoEdad: '6-9', comida: 'cena', textura: 'Triturado fino', etiquetas: ['puerro'],
    preparacion: 'Cuece la zanahoria y el puerro hasta que estén tiernos. Tritura con caldo de cocción y aceite de oliva hasta obtener una crema homogénea.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Puerro', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },

  // ---------------------------------------------------------------
  // 9-12 MESES · COMIDA (puré con grumos / trocitos blandos)
  // ---------------------------------------------------------------
  { id: 'c912-01', nombre: 'Arroz con pollo y verduras en trocitos', grupoEdad: '9-12', comida: 'comida', textura: 'Trocitos muy pequeños y blandos', etiquetas: ['pollo'],
    preparacion: 'Cuece el arroz, el pollo y las verduras por separado hasta que estén blandos. Corta el pollo y las verduras en trocitos muy pequeños y mezcla con el arroz.',
    ingredientes: [ { nombre: 'Arroz', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pollo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-02', nombre: 'Puré con grumos de patata, merluza y zanahoria', grupoEdad: '9-12', comida: 'comida', textura: 'Triturado con grumos', etiquetas: ['pescado'],
    preparacion: 'Cuece la patata, la merluza y la zanahoria hasta que estén tiernas. Chafa con un tenedor dejando pequeños grumos, sin triturar del todo.',
    ingredientes: [ { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Merluza', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-03', nombre: 'Ternera con puré de boniato y guisantes chafados', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['ternera', 'guisantes'],
    preparacion: 'Cuece la ternera, el boniato y los guisantes hasta que estén tiernos. Chafa el boniato y los guisantes con un tenedor y corta la ternera en trocitos pequeños.',
    ingredientes: [ { nombre: 'Ternera', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Guisantes', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-04', nombre: 'Pollo con puré de calabacín y patata en trocitos', grupoEdad: '9-12', comida: 'comida', textura: 'Trocitos pequeños y blandos', etiquetas: ['pollo'],
    preparacion: 'Cuece el pollo, el calabacín y la patata. Corta el pollo y la patata en trocitos pequeños y chafa el calabacín con un tenedor.',
    ingredientes: [ { nombre: 'Pechuga de pollo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-05', nombre: 'Pavo con crema de calabaza y arroz', grupoEdad: '9-12', comida: 'comida', textura: 'Triturado con grumos', etiquetas: ['pavo'],
    preparacion: 'Cuece el pavo, la calabaza y el arroz hasta que estén tiernos. Chafa la calabaza con un tenedor y corta el pavo en trocitos pequeños, mezclando con el arroz.',
    ingredientes: [ { nombre: 'Pechuga de pavo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Calabaza', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Arroz', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' } ] },
  { id: 'c912-06', nombre: 'Lentejas chafadas con verduras y patata', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['legumbres'],
    preparacion: 'Cuece las lentejas con la zanahoria y la patata hasta que estén muy tiernas. Chafa todo con un tenedor dejando una textura con grumos.',
    ingredientes: [ { nombre: 'Lentejas', cantidad: 40, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-07', nombre: 'Merluza con puré de brócoli y patata', grupoEdad: '9-12', comida: 'comida', textura: 'Triturado con grumos', etiquetas: ['pescado', 'brocoli'],
    preparacion: 'Cuece la merluza, el brócoli y la patata. Chafa el brócoli y la patata con un tenedor y desmenuza la merluza comprobando que no queden espinas.',
    ingredientes: [ { nombre: 'Merluza', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Brócoli', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-08', nombre: 'Tortilla francesa chafada con puré de calabacín', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['huevo'],
    preparacion: 'Cuaja el huevo batido en una sartén a fuego suave formando una tortilla francesa y trocéala muy fina. Cuece el calabacín y chafa con un tenedor; sirve ambos juntos.',
    ingredientes: [ { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-09', nombre: 'Pollo con cuscús chafado y zanahoria', grupoEdad: '9-12', comida: 'comida', textura: 'Trocitos pequeños y blandos', etiquetas: ['pollo', 'gluten'],
    preparacion: 'Cuece el cuscús según el envase y chafa con un tenedor. Cuece el pollo y la zanahoria, corta en trocitos pequeños y mezcla con el cuscús.',
    ingredientes: [ { nombre: 'Pechuga de pollo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Cuscús', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-10', nombre: 'Ternera con puré de guisantes y patata', grupoEdad: '9-12', comida: 'comida', textura: 'Triturado con grumos', etiquetas: ['ternera', 'guisantes'],
    preparacion: 'Cuece la ternera, los guisantes y la patata hasta que estén tiernos. Chafa los guisantes y la patata con un tenedor y corta la ternera en trocitos pequeños.',
    ingredientes: [ { nombre: 'Ternera', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Guisantes', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-11', nombre: 'Pollo con puré de espinacas y patata', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['pollo', 'espinacas'],
    preparacion: 'Cuece el pollo, las espinacas y la patata. Chafa las espinacas y la patata con un tenedor y corta el pollo en trocitos pequeños.',
    ingredientes: [ { nombre: 'Pechuga de pollo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Espinacas', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-12', nombre: 'Merluza con arroz y guisantes chafados', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['pescado', 'guisantes'],
    preparacion: 'Cuece la merluza, el arroz y los guisantes. Chafa los guisantes con un tenedor, desmenuza la merluza y mezcla con el arroz.',
    ingredientes: [ { nombre: 'Merluza', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Arroz', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Guisantes', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-13', nombre: 'Ternera con cuscús chafado y calabacín', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['ternera', 'gluten'],
    preparacion: 'Cuece la ternera y el calabacín; prepara el cuscús según el envase. Chafa el cuscús y el calabacín con un tenedor y corta la ternera en trocitos pequeños.',
    ingredientes: [ { nombre: 'Ternera', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Cuscús', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-14', nombre: 'Pavo con puré de coliflor y patata', grupoEdad: '9-12', comida: 'comida', textura: 'Triturado con grumos', etiquetas: ['pavo', 'coliflor'],
    preparacion: 'Cuece el pavo, la coliflor y la patata. Chafa la coliflor y la patata con un tenedor y corta el pavo en trocitos pequeños.',
    ingredientes: [ { nombre: 'Pechuga de pavo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Coliflor', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-15', nombre: 'Garbanzos chafados con verduras', grupoEdad: '9-12', comida: 'comida', textura: 'Chafado con tenedor', etiquetas: ['legumbres'],
    preparacion: 'Cuece los garbanzos (o usa cocidos) con la zanahoria y el calabacín hasta que estén tiernos. Chafa todo con un tenedor dejando una textura con grumos.',
    ingredientes: [ { nombre: 'Garbanzos cocidos', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c912-16', nombre: 'Salmón con puré de boniato y brócoli', grupoEdad: '9-12', comida: 'comida', textura: 'Triturado con grumos', etiquetas: ['pescado', 'brocoli'],
    preparacion: 'Cuece el salmón al vapor, el boniato y el brócoli. Chafa el boniato y el brócoli con un tenedor y desmenuza el salmón comprobando que no queden espinas.',
    ingredientes: [ { nombre: 'Salmón', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Brócoli', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' } ] },

  // ---------------------------------------------------------------
  // 9-12 MESES · CENA (ligera)
  // ---------------------------------------------------------------
  { id: 'n912-01', nombre: 'Crema de calabacín con quesito fresco', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['lacteos'],
    preparacion: 'Cuece el calabacín hasta que esté tierno y tritura con el quesito fresco hasta obtener una crema con pequeños grumos.',
    ingredientes: [ { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Queso fresco tipo Burgos', cantidad: 20, unidad: 'g', categoria: 'Lácteos y huevos' } ] },
  { id: 'n912-02', nombre: 'Puré de verduras variadas con aceite', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: [],
    preparacion: 'Cuece la zanahoria, la judía verde y la patata hasta que estén tiernas. Chafa con un tenedor y añade un chorrito de aceite de oliva.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Judía verde', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-03', nombre: 'Sopa de estrellitas con verdura chafada', grupoEdad: '9-12', comida: 'cena', textura: 'Trocitos pequeños', etiquetas: ['gluten'],
    preparacion: 'Cuece la pasta y la zanahoria en el mismo caldo. Chafa la zanahoria con un tenedor y mezcla con la pasta bien cocida.',
    ingredientes: [ { nombre: 'Pasta tipo estrellitas', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-04', nombre: 'Crema de calabaza con patata', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: [],
    preparacion: 'Cuece la calabaza y la patata hasta que estén muy tiernas. Chafa con un tenedor dejando pequeños grumos.',
    ingredientes: [ { nombre: 'Calabaza', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-05', nombre: 'Puré de brócoli y patata con queso fresco', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['brocoli', 'lacteos'],
    preparacion: 'Cuece el brócoli y la patata hasta que estén tiernos. Chafa con un tenedor y mezcla con el queso fresco.',
    ingredientes: [ { nombre: 'Brócoli', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Queso fresco tipo Burgos', cantidad: 20, unidad: 'g', categoria: 'Lácteos y huevos' } ] },
  { id: 'n912-06', nombre: 'Yogur natural con plátano chafado', grupoEdad: '9-12', comida: 'cena', textura: 'Chafado con tenedor', etiquetas: ['lacteos'],
    preparacion: 'Chafa el plátano maduro con un tenedor y mézclalo con el yogur natural hasta conseguir una crema con pequeños trozos.',
    ingredientes: [ { nombre: 'Yogur natural', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-07', nombre: 'Puré de guisantes y arroz', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['guisantes'],
    preparacion: 'Cuece los guisantes y el arroz hasta que estén tiernos. Chafa con un tenedor dejando una textura con grumos.',
    ingredientes: [ { nombre: 'Guisantes', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Arroz', cantidad: 25, unidad: 'g', categoria: 'Cereales y legumbres' } ] },
  { id: 'n912-08', nombre: 'Crema de puerro y patata', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['puerro'],
    preparacion: 'Cuece el puerro y la patata hasta que estén tiernos. Chafa con un tenedor dejando pequeños grumos.',
    ingredientes: [ { nombre: 'Puerro', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-09', nombre: 'Puré de zanahoria y boniato', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: [],
    preparacion: 'Cuece la zanahoria y el boniato hasta que estén tiernos. Chafa con un tenedor dejando una textura con grumos.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Boniato', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-10', nombre: 'Sopa de fideos finos con verdura', grupoEdad: '9-12', comida: 'cena', textura: 'Trocitos pequeños', etiquetas: ['gluten'],
    preparacion: 'Cuece los fideos y el calabacín en el mismo caldo hasta que estén blandos. Sirve troceando el calabacín muy fino.',
    ingredientes: [ { nombre: 'Fideos finos', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-11', nombre: 'Crema de espinacas con patata', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['espinacas'],
    preparacion: 'Cuece las espinacas y la patata hasta que estén tiernas. Chafa con un tenedor dejando pequeños grumos.',
    ingredientes: [ { nombre: 'Espinacas', cantidad: 80, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-12', nombre: 'Puré de coliflor con queso fresco', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['coliflor', 'lacteos'],
    preparacion: 'Cuece la coliflor hasta que esté tierna. Chafa con un tenedor y mezcla con el queso fresco.',
    ingredientes: [ { nombre: 'Coliflor', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Queso fresco tipo Burgos', cantidad: 20, unidad: 'g', categoria: 'Lácteos y huevos' } ] },
  { id: 'n912-13', nombre: 'Crema de zanahoria con arroz', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: [],
    preparacion: 'Cuece la zanahoria y el arroz hasta que estén tiernos. Chafa con un tenedor dejando una textura con grumos.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Arroz', cantidad: 25, unidad: 'g', categoria: 'Cereales y legumbres' } ] },
  { id: 'n912-14', nombre: 'Puré de manzana y pera', grupoEdad: '9-12', comida: 'cena', textura: 'Chafado con tenedor', etiquetas: ['manzana'],
    preparacion: 'Cuece la manzana y la pera peladas y troceadas hasta que estén tiernas. Chafa con un tenedor dejando pequeños trocitos.',
    ingredientes: [ { nombre: 'Manzana', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pera', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-15', nombre: 'Sopa de arroz con verduritas', grupoEdad: '9-12', comida: 'cena', textura: 'Trocitos pequeños', etiquetas: [],
    preparacion: 'Cuece el arroz con la zanahoria y el calabacín troceados muy finos hasta que todo esté tierno.',
    ingredientes: [ { nombre: 'Arroz', cantidad: 25, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n912-16', nombre: 'Puré de calabacín con queso fresco', grupoEdad: '9-12', comida: 'cena', textura: 'Triturado con grumos', etiquetas: ['lacteos'],
    preparacion: 'Cuece el calabacín hasta que esté tierno. Chafa con un tenedor y mezcla con el queso fresco.',
    ingredientes: [ { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Queso fresco tipo Burgos', cantidad: 20, unidad: 'g', categoria: 'Lácteos y huevos' } ] },

  // ---------------------------------------------------------------
  // 1-5 AÑOS · COMIDA (sólido)
  // ---------------------------------------------------------------
  { id: 'c15-01', nombre: 'Arroz con pollo y verduras salteadas', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pollo'],
    preparacion: 'Cuece el arroz. Saltea el pollo troceado con el pimiento y la zanahoria en una sartén con un poco de aceite hasta que estén dorados y tiernos. Mezcla con el arroz.',
    ingredientes: [ { nombre: 'Arroz', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pollo', cantidad: 80, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Pimiento', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-02', nombre: 'Merluza al horno con puré de patata y zanahoria', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pescado'],
    preparacion: 'Hornea la merluza a 180°C durante 12-15 minutos con un chorrito de aceite. Cuece la patata y la zanahoria y haz un puré chafándolas con un tenedor o pasapurés.',
    ingredientes: [ { nombre: 'Merluza', cantidad: 90, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Patata', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-03', nombre: 'Pasta con tomate y albóndigas de pavo', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pavo', 'gluten', 'tomate'],
    preparacion: 'Cuece la pasta. Forma albóndigas con la carne picada de pavo y cocínalas en la salsa de tomate a fuego suave durante 10-15 minutos. Sirve sobre la pasta.',
    ingredientes: [ { nombre: 'Pasta', cantidad: 70, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Carne picada de pavo', cantidad: 70, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Tomate triturado', cantidad: 150, unidad: 'g', categoria: 'Otros' } ] },
  { id: 'c15-04', nombre: 'Lentejas estofadas con verduras', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['legumbres'],
    preparacion: 'Sofríe la cebolla, añade las lentejas, la zanahoria y la patata troceadas, cubre con agua y cuece a fuego medio 30-40 minutos hasta que estén tiernas.',
    ingredientes: [ { nombre: 'Lentejas', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Cebolla', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-05', nombre: 'Pollo asado con puré de boniato', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pollo'],
    preparacion: 'Hornea el muslo de pollo a 200°C durante 30-35 minutos hasta que esté dorado. Cuece el boniato y hazlo puré chafándolo con un tenedor.',
    ingredientes: [ { nombre: 'Muslo de pollo', cantidad: 100, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Boniato', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-06', nombre: 'Tortilla de patata con ensalada de tomate', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['huevo', 'tomate'],
    preparacion: 'Cuece o fríe la patata en láminas finas, mezcla con el huevo batido y cuaja en una sartén por ambos lados. Sirve con el tomate cortado en trocitos.',
    ingredientes: [ { nombre: 'Huevo', cantidad: 2, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Patata', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Tomate', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-07', nombre: 'Salmón al vapor con arroz y brócoli', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pescado', 'brocoli'],
    preparacion: 'Cuece el salmón al vapor unos 10 minutos. Cuece el arroz y el brócoli por separado y sirve todo junto.',
    ingredientes: [ { nombre: 'Salmón', cantidad: 80, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Arroz', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Brócoli', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-08', nombre: 'Garbanzos con verduras (potaje)', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['legumbres'],
    preparacion: 'Cuece los garbanzos (o usa cocidos) con la acelga y la zanahoria troceadas durante 20 minutos a fuego medio hasta que las verduras estén tiernas.',
    ingredientes: [ { nombre: 'Garbanzos cocidos', cantidad: 80, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Acelga', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-09', nombre: 'Ternera guisada con patatas y zanahoria', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['ternera'],
    preparacion: 'Dora la ternera troceada en una cazuela, añade la patata y la zanahoria, cubre con agua o caldo y cuece a fuego lento 40-50 minutos hasta que esté tierna.',
    ingredientes: [ { nombre: 'Ternera', cantidad: 90, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Patata', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-10', nombre: 'Pasta integral con verduras y pavo', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pavo', 'gluten'],
    preparacion: 'Cuece la pasta. Saltea el pavo troceado con el calabacín en una sartén con un poco de aceite y mezcla con la pasta.',
    ingredientes: [ { nombre: 'Pasta integral', cantidad: 70, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pavo', cantidad: 70, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-11', nombre: 'Quinoa con verduras y huevo poché', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['huevo'],
    preparacion: 'Cuece la quinoa según el envase. Saltea el pimiento y escalfa el huevo en agua caliente con un chorrito de vinagre. Sirve la quinoa con el pimiento y el huevo poché.',
    ingredientes: [ { nombre: 'Quinoa', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Pimiento', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-12', nombre: 'Muslitos de pollo al horno con puré de calabaza', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pollo'],
    preparacion: 'Hornea los muslos de pollo a 200°C durante 30-35 minutos. Cuece la calabaza y hazla puré chafándola con un tenedor.',
    ingredientes: [ { nombre: 'Muslo de pollo', cantidad: 100, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Calabaza', cantidad: 200, unidad: 'g', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-13', nombre: 'Espaguetis con verduras y atún', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pescado', 'gluten', 'tomate'],
    preparacion: 'Cuece los espaguetis. Saltea el calabacín y el tomate troceados, añade el atún desmenuzado y mezcla con la pasta.',
    ingredientes: [ { nombre: 'Espaguetis', cantidad: 70, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Atún al natural', cantidad: 80, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Calabacín', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Tomate', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-14', nombre: 'Pollo al curry suave con arroz', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pollo', 'lacteos'],
    preparacion: 'Cuece el arroz. Cocina el pollo troceado en una sartén, añade la leche y el curry suave y cuece a fuego lento 10 minutos hasta que espese ligeramente. Sirve con el arroz.',
    ingredientes: [ { nombre: 'Pechuga de pollo', cantidad: 90, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Arroz', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Leche', cantidad: 100, unidad: 'ml', categoria: 'Lácteos y huevos' }, { nombre: 'Curry suave', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'c15-15', nombre: 'Albóndigas de ternera con puré de patata', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['ternera', 'huevo', 'gluten'],
    preparacion: 'Mezcla la carne picada con el huevo y el pan rallado, forma albóndigas y cocínalas en una sartén con un poco de aceite. Cuece la patata y haz un puré.',
    ingredientes: [ { nombre: 'Carne picada de ternera', cantidad: 90, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Patata', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Pan rallado', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' } ] },
  { id: 'c15-16', nombre: 'Judías verdes con patata y huevo cocido', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['huevo'],
    preparacion: 'Cuece la judía verde y la patata hasta que estén tiernas. Cuece el huevo 10 minutos, pélalo y córtalo en trozos para acompañar.',
    ingredientes: [ { nombre: 'Judía verde', cantidad: 150, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Patata', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' } ] },
  { id: 'c15-17', nombre: 'Arroz tres delicias casero con pollo y verduras', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pollo', 'huevo', 'guisantes'],
    preparacion: 'Cuece el arroz y déjalo enfriar. Saltea el pollo troceado, el huevo revuelto, los guisantes y la zanahoria y mezcla todo con el arroz.',
    ingredientes: [ { nombre: 'Arroz', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pollo', cantidad: 60, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Guisantes', cantidad: 50, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'c15-18', nombre: 'Merluza a la plancha con ensalada de arroz', grupoEdad: '1-5', comida: 'comida', textura: 'Sólido', etiquetas: ['pescado', 'tomate'],
    preparacion: 'Cocina la merluza a la plancha con un chorrito de aceite. Cuece el arroz y mézclalo con el tomate y la lechuga troceados.',
    ingredientes: [ { nombre: 'Merluza', cantidad: 90, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Arroz', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Tomate', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Lechuga', cantidad: 1, unidad: 'puñado', categoria: 'Frutas y verduras' } ] },

  // ---------------------------------------------------------------
  // 1-5 AÑOS · CENA (ligera)
  // ---------------------------------------------------------------
  { id: 'n15-01', nombre: 'Crema de calabacín con picatostes', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['gluten'], ligera: true,
    preparacion: 'Cuece el calabacín hasta que esté tierno y tritura hasta obtener una crema fina. Tuesta el pan cortado en dados y añádelo por encima antes de servir.',
    ingredientes: [ { nombre: 'Calabacín', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pan', cantidad: 1, unidad: 'rebanada', categoria: 'Cereales y legumbres' } ] },
  { id: 'n15-02', nombre: 'Tortilla francesa con puré de patata', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['huevo'], ligera: true,
    preparacion: 'Bate el huevo y cuaja en una sartén formando una tortilla francesa. Cuece la patata y hazla puré chafándola con un tenedor.',
    ingredientes: [ { nombre: 'Huevo', cantidad: 2, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Patata', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n15-03', nombre: 'Sopa de pollo con fideos', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['pollo', 'gluten'], ligera: true,
    preparacion: 'Cuece el pollo troceado en agua o caldo, añade los fideos los últimos 5 minutos y cuece hasta que estén blandos.',
    ingredientes: [ { nombre: 'Pechuga de pollo', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Fideos finos', cantidad: 40, unidad: 'g', categoria: 'Cereales y legumbres' } ] },
  { id: 'n15-04', nombre: 'Puré de verduras con queso fresco', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['lacteos'], ligera: true,
    preparacion: 'Cuece la zanahoria y el puerro hasta que estén tiernos y tritura con el queso fresco hasta obtener una crema.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Puerro', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Queso fresco tipo Burgos', cantidad: 30, unidad: 'g', categoria: 'Lácteos y huevos' } ] },
  { id: 'n15-05', nombre: 'Revuelto de huevo con espinacas', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['huevo', 'espinacas'], ligera: true,
    preparacion: 'Saltea las espinacas en una sartén con un poco de aceite hasta que reduzcan, añade el huevo batido y cuaja removiendo a fuego suave.',
    ingredientes: [ { nombre: 'Huevo', cantidad: 2, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Espinacas', cantidad: 100, unidad: 'g', categoria: 'Frutas y verduras' } ] },
  { id: 'n15-06', nombre: 'Crema de calabaza con pan tostado', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['gluten'], ligera: true,
    preparacion: 'Cuece la calabaza hasta que esté tierna y tritura hasta obtener una crema fina. Tuesta el pan y sirve acompañando o troceado por encima.',
    ingredientes: [ { nombre: 'Calabaza', cantidad: 200, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Pan', cantidad: 1, unidad: 'rebanada', categoria: 'Cereales y legumbres' } ] },
  { id: 'n15-07', nombre: 'Yogur con fruta y cereales', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['lacteos'], ligera: true,
    preparacion: 'Corta el plátano en rodajas y mézclalo con el yogur natural y los copos de avena justo antes de servir.',
    ingredientes: [ { nombre: 'Yogur natural', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Copos de avena', cantidad: 20, unidad: 'g', categoria: 'Cereales y legumbres' } ] },
  { id: 'n15-08', nombre: 'Pescado blanco al horno con puré de zanahoria', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['pescado'], ligera: true,
    preparacion: 'Hornea la merluza a 180°C durante 12-15 minutos con un chorrito de aceite. Cuece la zanahoria y hazla puré chafándola con un tenedor.',
    ingredientes: [ { nombre: 'Merluza', cantidad: 80, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Zanahoria', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n15-09', nombre: 'Croquetas caseras de pollo con ensalada', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['pollo', 'gluten', 'lacteos'],
    preparacion: 'Prepara una bechamel con la leche, mezcla con el pollo cocido y desmenuzado, deja enfriar, forma las croquetas y dóralas en la sartén. Sirve con la lechuga.',
    ingredientes: [ { nombre: 'Pechuga de pollo', cantidad: 60, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Leche', cantidad: 100, unidad: 'ml', categoria: 'Lácteos y huevos' }, { nombre: 'Lechuga', cantidad: 1, unidad: 'puñado', categoria: 'Frutas y verduras' } ] },
  { id: 'n15-10', nombre: 'Sándwich integral de pavo y queso con tomate', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['pavo', 'gluten', 'lacteos', 'tomate'],
    preparacion: 'Monta el sándwich colocando el pavo, el queso y el tomate en rodajas entre las dos rebanadas de pan integral.',
    ingredientes: [ { nombre: 'Pan de molde integral', cantidad: 2, unidad: 'rebanada', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pavo cocida', cantidad: 40, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Queso en lonchas', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Tomate', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n15-11', nombre: 'Crema de zanahoria con queso fresco', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['lacteos'], ligera: true,
    preparacion: 'Cuece la zanahoria hasta que esté tierna y tritura con el queso fresco hasta obtener una crema fina.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 3, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Queso fresco tipo Burgos', cantidad: 30, unidad: 'g', categoria: 'Lácteos y huevos' } ] },
  { id: 'n15-12', nombre: 'Ensalada templada de pasta con atún', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['pescado', 'gluten', 'tomate'],
    preparacion: 'Cuece la pasta, escúrrela y mézclala templada con el atún desmenuzado y el tomate troceado.',
    ingredientes: [ { nombre: 'Pasta', cantidad: 60, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Atún al natural', cantidad: 80, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Tomate', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'n15-13', nombre: 'Puré de coliflor con jamón cocido', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['coliflor'], ligera: true,
    preparacion: 'Cuece la coliflor hasta que esté tierna y tritura hasta obtener una crema fina. Añade el jamón cocido cortado en trocitos por encima.',
    ingredientes: [ { nombre: 'Coliflor', cantidad: 200, unidad: 'g', categoria: 'Frutas y verduras' }, { nombre: 'Jamón cocido', cantidad: 30, unidad: 'g', categoria: 'Carnes y pescados' } ] },
  { id: 'n15-14', nombre: 'Tortitas de avena y plátano', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['huevo'], ligera: true,
    preparacion: 'Chafa el plátano con un tenedor y mézclalo con el huevo batido y los copos de avena hasta formar una masa. Cocina pequeñas tortitas en una sartén antiadherente por ambos lados.',
    ingredientes: [ { nombre: 'Copos de avena', cantidad: 40, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' } ] },
  { id: 'n15-15', nombre: 'Crema de puerro con picatostes', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['puerro', 'gluten'], ligera: true,
    preparacion: 'Cuece el puerro hasta que esté tierno y tritura hasta obtener una crema fina. Tuesta el pan cortado en dados y añádelo por encima.',
    ingredientes: [ { nombre: 'Puerro', cantidad: 2, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pan', cantidad: 1, unidad: 'rebanada', categoria: 'Cereales y legumbres' } ] },
  { id: 'n15-16', nombre: 'Wrap integral de pollo y verduras', grupoEdad: '1-5', comida: 'cena', textura: 'Sólido', etiquetas: ['pollo', 'gluten', 'tomate'],
    preparacion: 'Rellena la tortilla integral con el pollo cocido troceado, la lechuga y el tomate, y enróllala bien apretada.',
    ingredientes: [ { nombre: 'Tortilla de trigo integral', cantidad: 1, unidad: 'ud', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pollo cocida', cantidad: 50, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Lechuga', cantidad: 1, unidad: 'puñado', categoria: 'Frutas y verduras' }, { nombre: 'Tomate', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' } ] },

  // ---------------------------------------------------------------
  // 6-9 MESES · MERIENDA (puré de fruta)
  // ---------------------------------------------------------------
  { id: 'm69-01', nombre: 'Puré de manzana', grupoEdad: '6-9', comida: 'merienda', textura: 'Triturado fino', etiquetas: ['manzana'],
    preparacion: 'Cuece la manzana pelada y troceada con un poco de agua hasta que esté tierna. Tritura hasta obtener un puré fino.',
    ingredientes: [ { nombre: 'Manzana', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm69-02', nombre: 'Puré de pera', grupoEdad: '6-9', comida: 'merienda', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Cuece la pera pelada y troceada con un poco de agua hasta que esté tierna. Tritura hasta obtener un puré fino.',
    ingredientes: [ { nombre: 'Pera', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm69-03', nombre: 'Puré de plátano', grupoEdad: '6-9', comida: 'merienda', textura: 'Triturado fino', etiquetas: [],
    preparacion: 'Chafa el plátano maduro con un tenedor hasta obtener un puré fino y sin grumos.',
    ingredientes: [ { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm69-04', nombre: 'Puré de manzana y pera', grupoEdad: '6-9', comida: 'merienda', textura: 'Triturado fino', etiquetas: ['manzana'],
    preparacion: 'Cuece la manzana y la pera peladas y troceadas hasta que estén tiernas. Tritura hasta obtener un puré fino.',
    ingredientes: [ { nombre: 'Manzana', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pera', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },

  // ---------------------------------------------------------------
  // 9-12 MESES · MERIENDA
  // ---------------------------------------------------------------
  { id: 'm912-01', nombre: 'Plátano chafado con yogur natural', grupoEdad: '9-12', comida: 'merienda', textura: 'Chafado con tenedor', etiquetas: ['lacteos'],
    preparacion: 'Chafa el plátano con un tenedor y mézclalo con el yogur natural.',
    ingredientes: [ { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Yogur natural', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' } ] },
  { id: 'm912-02', nombre: 'Manzana asada chafada', grupoEdad: '9-12', comida: 'merienda', textura: 'Chafado con tenedor', etiquetas: ['manzana'],
    preparacion: 'Hornea la manzana entera a 180°C durante 20-25 minutos hasta que esté blanda. Pélala y chafa la pulpa con un tenedor.',
    ingredientes: [ { nombre: 'Manzana', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm912-03', nombre: 'Pera chafada con galleta María', grupoEdad: '9-12', comida: 'merienda', textura: 'Chafado con tenedor', etiquetas: ['gluten'],
    preparacion: 'Chafa la pera madura con un tenedor. Desmenuza la galleta y mézclala con el puré justo antes de servir.',
    ingredientes: [ { nombre: 'Pera', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Galleta María', cantidad: 1, unidad: 'ud', categoria: 'Cereales y legumbres' } ] },
  { id: 'm912-04', nombre: 'Aguacate chafado sobre tostada blanda', grupoEdad: '9-12', comida: 'merienda', textura: 'Chafado con tenedor', etiquetas: ['gluten'],
    preparacion: 'Chafa el aguacate con un tenedor y extiéndelo sobre pan tierno cortado en trocitos pequeños.',
    ingredientes: [ { nombre: 'Aguacate', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pan', cantidad: 1, unidad: 'rebanada', categoria: 'Cereales y legumbres' } ] },

  // ---------------------------------------------------------------
  // 1-5 AÑOS · MERIENDA
  // ---------------------------------------------------------------
  { id: 'm15-01', nombre: 'Bocadillo de jamón y queso', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['gluten', 'lacteos'],
    preparacion: 'Rellena el pan con el jamón cocido y el queso.',
    ingredientes: [ { nombre: 'Pan', cantidad: 1, unidad: 'ud', categoria: 'Cereales y legumbres' }, { nombre: 'Jamón cocido', cantidad: 20, unidad: 'g', categoria: 'Carnes y pescados' }, { nombre: 'Queso en lonchas', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' } ] },
  { id: 'm15-02', nombre: 'Bocadillo de pavo', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['pavo', 'gluten'],
    preparacion: 'Rellena el pan con la pechuga de pavo cocida.',
    ingredientes: [ { nombre: 'Pan', cantidad: 1, unidad: 'ud', categoria: 'Cereales y legumbres' }, { nombre: 'Pechuga de pavo cocida', cantidad: 20, unidad: 'g', categoria: 'Carnes y pescados' } ] },
  { id: 'm15-03', nombre: 'Fruta de temporada', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: [],
    preparacion: 'Lava y corta la fruta en trozos del tamaño adecuado para que la coma con la mano o con un tenedor.',
    ingredientes: [ { nombre: 'Fruta de temporada', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm15-04', nombre: 'Yogur con galletas', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['lacteos', 'gluten'],
    preparacion: 'Sirve el yogur con las galletas para untar o desmenuzar por encima.',
    ingredientes: [ { nombre: 'Yogur natural', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Galletas María', cantidad: 2, unidad: 'ud', categoria: 'Cereales y legumbres' } ] },
  { id: 'm15-05', nombre: 'Batido de plátano con leche', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['lacteos'],
    preparacion: 'Tritura el plátano con la leche hasta obtener un batido homogéneo.',
    ingredientes: [ { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Leche', cantidad: 150, unidad: 'ml', categoria: 'Lácteos y huevos' } ] },
  { id: 'm15-06', nombre: 'Palitos de zanahoria y pepino con hummus', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['legumbres'],
    preparacion: 'Corta la zanahoria y el pepino en palitos y sírvelos para mojar en el hummus.',
    ingredientes: [ { nombre: 'Zanahoria', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pepino', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Hummus', cantidad: 40, unidad: 'g', categoria: 'Otros' } ] },
  { id: 'm15-07', nombre: 'Tortitas de avena caseras', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['huevo'],
    preparacion: 'Bate el huevo con los copos de avena y el plátano chafado. Cocina pequeñas tortitas en una sartén antiadherente por ambos lados.',
    ingredientes: [ { nombre: 'Copos de avena', cantidad: 30, unidad: 'g', categoria: 'Cereales y legumbres' }, { nombre: 'Huevo', cantidad: 1, unidad: 'ud', categoria: 'Lácteos y huevos' }, { nombre: 'Plátano', cantidad: 1, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm15-08', nombre: 'Macedonia de frutas', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: [],
    preparacion: 'Corta la fruta en trozos pequeños y mézclala en un bol.',
    ingredientes: [ { nombre: 'Manzana', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Plátano', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Pera', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' } ] },
  { id: 'm15-09', nombre: 'Pan con tomate y aceite', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['gluten', 'tomate'],
    preparacion: 'Unta el pan con el tomate rallado y añade un chorrito de aceite de oliva.',
    ingredientes: [ { nombre: 'Pan', cantidad: 1, unidad: 'ud', categoria: 'Cereales y legumbres' }, { nombre: 'Tomate', cantidad: 0.5, unidad: 'ud', categoria: 'Frutas y verduras' }, { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'cucharadita', categoria: 'Otros' } ] },
  { id: 'm15-10', nombre: 'Queso fresco con membrillo', grupoEdad: '1-5', comida: 'merienda', textura: 'Sólido', etiquetas: ['lacteos'],
    preparacion: 'Corta el queso fresco en dados y sírvelo con el membrillo en trocitos.',
    ingredientes: [ { nombre: 'Queso fresco tipo Burgos', cantidad: 40, unidad: 'g', categoria: 'Lácteos y huevos' }, { nombre: 'Dulce de membrillo', cantidad: 20, unidad: 'g', categoria: 'Otros' } ] },
];

// Alérgenos que se pueden excluir de forma estricta
const ALERGENOS = [
  { id: 'gluten', etiqueta: 'gluten', nombre: 'Gluten' },
  { id: 'lacteos', etiqueta: 'lacteos', nombre: 'Lácteos' },
  { id: 'huevo', etiqueta: 'huevo', nombre: 'Huevo' },
  { id: 'pescado', etiqueta: 'pescado', nombre: 'Pescado' },
  { id: 'frutos-secos', etiqueta: 'frutos-secos', nombre: 'Frutos secos' },
  { id: 'legumbres', etiqueta: 'legumbres', nombre: 'Legumbres' },
];

// Ingredientes/sabores habituales que un niño puede rechazar
const NO_GUSTA_OPCIONES = [
  { id: 'pescado', etiqueta: 'pescado', nombre: 'Pescado' },
  { id: 'brocoli', etiqueta: 'brocoli', nombre: 'Brócoli' },
  { id: 'coliflor', etiqueta: 'coliflor', nombre: 'Coliflor' },
  { id: 'espinacas', etiqueta: 'espinacas', nombre: 'Espinacas' },
  { id: 'acelga', etiqueta: 'acelga', nombre: 'Acelga' },
  { id: 'puerro', etiqueta: 'puerro', nombre: 'Puerro' },
  { id: 'guisantes', etiqueta: 'guisantes', nombre: 'Guisantes' },
  { id: 'legumbres', etiqueta: 'legumbres', nombre: 'Legumbres' },
  { id: 'huevo', etiqueta: 'huevo', nombre: 'Huevo' },
  { id: 'tomate', etiqueta: 'tomate', nombre: 'Tomate' },
  { id: 'ternera', etiqueta: 'ternera', nombre: 'Ternera' },
  { id: 'pavo', etiqueta: 'pavo', nombre: 'Pavo' },
  { id: 'pollo', etiqueta: 'pollo', nombre: 'Pollo' },
];

const ETAPAS = {
  '6-9': { nombre: '6-9 meses', descripcionTextura: 'Puré fino y colado' },
  '9-12': { nombre: '9-12 meses', descripcionTextura: 'Puré con grumos / trocitos blandos' },
  '1-5': { nombre: '1-5 años', descripcionTextura: 'Alimentación sólida' },
};

const DIAS_SEMANA = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'];
const DIAS_SEMANA_LABEL = { lunes: 'Lunes', martes: 'Martes', miercoles: 'Miércoles', jueves: 'Jueves', viernes: 'Viernes', sabado: 'Sábado', domingo: 'Domingo' };

// Tipos de comida planificables, en el orden en que se muestran
const TIPOS_COMIDA = ['comida', 'merienda', 'cena'];
const TIPOS_COMIDA_LABEL = { comida: 'Comida', merienda: 'Merienda', cena: 'Cena' };

// Palabras clave para clasificar el plato del comedor escolar y sugerir una cena equilibrada
const REGLAS_EQUILIBRIO = {
  proteinas: {
    pollo: ['pollo', 'pavo'],
    ternera: ['ternera', 'carne', 'filete', 'albóndiga', 'albondiga', 'ragout'],
    pescado: ['pescado', 'merluza', 'salmón', 'salmon', 'lenguado', 'bacalao', 'atún', 'atun', 'dorada', 'gallo'],
    huevo: ['huevo', 'tortilla'],
    legumbres: ['lentejas', 'garbanzos', 'alubias', 'judías blancas', 'judias blancas', 'potaje', 'fabada'],
  },
  copioso: ['hamburguesa', 'frito', 'fritos', 'empanadilla', 'croqueta', 'pizza', 'rebozado', 'san jacobo', 'nugget', 'patatas fritas', 'cocido', 'lasaña', 'canelones'],
};
